### PR TITLE
remove event listener fix

### PR DESCRIPTION
**Pull request by vishnu-ravi**

### CODE REVIEW

**Review by meelie — COMMENTED** [review]
I'll test it tomorrow.
- Can you fix the rebase issue of the PR?
- can you explain in PR comment what was the issue and how the fix will fix it ?
Thanks

**Comment by vishnu-ravi** [comment]
When we change assistant, yeldaChat.resetChat is called, it removes the window.onmessage event listener. which was not removed properly leads to multiple openChat event triggered so these issues occur 
https://github.com/Yeldaai/yelda/issues/4319
https://github.com/Yeldaai/yelda/issues/4318
https://github.com/Yeldaai/yelda/issues/4301
To fix these issues remove event listener is fixed in chatPlugin and webchat repos

**Review by meelie — APPROVED** [review]
ok, let's try, thanks
i accept, but i let you do the plugin update on your side and merge after that
thanks

**Review by meelie — APPROVED** [review]
ok, i let you update yelda + preview `yelda-webchat` npm package + webchat build !
Thanks

**Pull request merged**
